windowrule = match:class steam, workspace 3
windowrule = match:class steam, fullscreen on
windowrule = match:class firefox, workspace 2
windowrule = match:class discord, workspace 1
windowrule = match:class slack, workspace 1
windowrule = match:class obsidian, workspace 4

windowrule = match:fullscreen 1, border_color rgb(A78BFA)
windowrule = match:fullscreen 1, border_size 4
windowrule = match:class Rofi, float on
windowrule = match:class feh, float on

windowrule = match:class floating, float on
windowrule = match:class floating, stay_focused on
windowrule = match:class firefox, match:title Library, float on
windowrule = match:class firefox, match:title Library, stay_focused on

# layerrule = match:namespace .*, blur on
layerrule = match:namespace rofi, ignore_alpha 0
